---
# tasks file for auth_proxy

# Load the auth-proxy-image from local tar. Ignore any errors to handle the
# case where the image is not built in
- name: copy auth-proxy image
  copy: src={{ auth_proxy_binaries }}/auth-proxy-image.tar dest=/tmp/auth-proxy-image.tar
  ignore_errors: yes

- name: load auth-proxy image
  shell: docker load -i /tmp/auth-proxy-image.tar
  ignore_errors: yes

- name: create cert folder for proxy
  file: path=/var/contiv/certs state=directory

- name: copy shell script for starting auth-proxy
  template: src=auth_proxy.j2 dest=/usr/bin/auth_proxy.sh mode=u=rwx,g=rx,o=rx

- name: copy cert for starting auth-proxy
  copy: src=cert.pem dest=/var/contiv/certs/auth_proxy_cert.pem mode=u=rw,g=r,o=r

- name: copy key for starting auth-proxy
  copy: src=key.pem dest=/var/contiv/certs/auth_proxy_key.pem mode=u=rw,g=r,o=r

- name: copy systemd units for auth-proxy
  copy: src=auth-proxy.service dest=/etc/systemd/system/auth-proxy.service

- name: initialize auth-proxy
  shell: /usr/bin/auth_proxy.sh init

- name: start auth-proxy container
  systemd: name=auth-proxy daemon_reload=yes state=started enabled=yes
