# These tasks are run when contiv_network_mode is set to aci

# Load the aci-gw-image from local tar. Ignore any errors to handle the
# case where the image is not built in
- name: copy aci-gw image
  copy: src={{ contiv_standalone_binaries }}/aci-gw-image.tar dest=/tmp/aci-gw-image.tar
  when: contiv_network_local_install == True

- name: load aci-gw image
  shell: docker load -i /tmp/aci-gw-image.tar
  when: contiv_network_local_install == True

# For non-local installs pull the aci-gw image. Ignore errors if the image pull times out.
# It will be loaded on docker run
- name: pull aci-gw image
  shell: docker pull {{ aci_gw_image }}
  when: contiv_network_local_install == False

- name: copy shell script for starting aci-gw
  template: src=aci_gw.j2 dest=/usr/bin/aci_gw.sh mode=u=rwx,g=rx,o=rx

- name: copy systemd units for aci-gw
  copy: src=aci-gw.service dest=/etc/systemd/system/aci-gw.service

- name: start aci-gw container
  systemd: name=aci-gw daemon_reload=yes state=started enabled=yes

- name: set aci mode
  shell: netctl --netmaster {{ netctl_url }} global set --fabric-mode aci
  run_once: true
