---
# This role contains tasks for installing ovs
- name: get openstack kilo repo
  get_url:
    url: https://repos.fedorapeople.org/repos/openstack/openstack-kilo/rdo-release-kilo-2.noarch.rpm
    dest: /tmp/rdo-release-kilo-2.noarch.rpm
    validate_certs: false
  when: ansible_os_family == "RedHat"
  tags:
    - prebake-for-dev

- name: install openstack kilo rpm
  yum: name=/tmp/rdo-release-kilo-2.noarch.rpm state=present
  when: ansible_os_family == "RedHat"
  tags:
    - prebake-for-dev

- name: disable openstack kilo repo
  ini_file:
    dest: /etc/yum.repos.d/rdo-release.repo
    section: openstack-kilo
    option: enabled
    value: 0
    mode: 0644
    backup: no
  when: ansible_os_family == "RedHat"
  tags:
    - prebake-for-dev

- name: install ovs
  yum:
    pkg=openvswitch-2.5.0-2.el7.x86_64
    state=present
    enablerepo=openstack-kilo
  when: ansible_os_family == "RedHat"
  tags:
    - prebake-for-dev

- name: install ovs-common (debian)
  apt: 
      name: openvswitch-common=2.5.*
      state: present
  when: ansible_os_family == "Debian"
  tags:
    - prebake-for-dev

- name: install ovs (debian)
  apt: 
      name: openvswitch-switch=2.5.*
      state: present
  when: ansible_os_family == "Debian"
  tags:
    - prebake-for-dev

- name: start ovs service
  systemd: name=openvswitch daemon_reload=yes enabled=yes state=started
  when: ansible_os_family == "RedHat"

- name: setup ovs
  shell: "ovs-vsctl set-manager {{ item }}"
  with_items:
    - "tcp:127.0.0.1:6640"
    - "ptcp:6640"

- name: check selinux status
  shell: sestatus
  register: selinux_set
  when: (ansible_os_family == "RedHat")

- name: permit openvswitch_t type in selinux
  shell: >
      semanage permissive -a openvswitch_t
  when: (ansible_os_family == "RedHat") and (selinux_set.stdout | search(".*SELinux status:.*enabled.*"))
  become: true

- name: setup iptables for vxlan vtep port
  shell: >
      ( iptables -L INPUT | grep "{{ netplugin_rule_comment }} ({{ item }})" ) || \
      iptables -I INPUT 1 -p udp --dport {{ item }} -j ACCEPT -m comment --comment "{{ netplugin_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ vxlan_port }}"
