---

# Role defaults for contiv_network & v2plugin
# NOTE: Role defaults have a lower priority than inventory vars.
# Include variables which need to be overridden by inventory vars here.

contiv_v2plugin_image: "contiv/v2plugin:{{ contiv_network_version }}"
contiv_v2plugin_tar_filename: "v2plugin-{{ contiv_network_version }}.tar.gz"

contiv_network_mode: "standalone" # Accepted values: standalone, aci
netplugin_mode: "docker" # Accepted values: docker, kubernetes
fwd_mode: "bridge" #Accepted values: bridge , routing
listen_url: ":9999"
control_url: ":9999"
netctl_url: "http://netmaster:9999"
cluster_store_url: "http://127.0.0.1:2379"
cluster_store_driver: etcd
contiv_standalone_binaries: "/var/contiv_cache"
ofnet_master_port: 9001
ofnet_agent_port1: 9002
ofnet_agent_port2: 9003
netmaster_port: 9999
gobgp_grpc_port: 8080
bgp_port: 179
# Since there is a conflict on vxlan port used by Docker overlay (ingress)
# contiv needs to use a different port than the standard 4789 for v2plugin
# vxlan_port: 8472
vxlan_port: 4789
netplugin_rule_comment: "contiv_network traffic"

aci_gw_image: "contiv/aci-gw"
# contiv tar files to get netplugin binary
contiv_network_version: "1.1.7"
contiv_network_tar_file: "netplugin-{{ contiv_network_version }}.tar.bz2"
contiv_network_src_tar_file: "{{ contiv_standalone_binaries }}/{{ contiv_network_tar_file }}"
contiv_network_src_file: "https://github.com/contiv/netplugin/releases/download/{{ contiv_network_version }}/{{ contiv_network_tar_file }}"
contiv_network_dest_file: "/tmp/{{ contiv_network_tar_file }}"

apic_epg_bridge_domain: "not_specified"
apic_contracts_unrestricted_mode: "no"

contiv_network_k8s_config_dir: "/opt/contiv/config/"
contiv_network_local_install: False
