---
# This play contains tasks for cleaning up v2plugin services

- name: stop aci-gw container
  service: name=aci-gw state=stopped

- name: uninstall v2plugin on nodes
  shell: >
      (/usr/bin/docker plugin disable {{ contiv_v2plugin_image }}) && /usr/bin/docker plugin rm -f {{ contiv_v2plugin_image }}

- name: cleanup netmaster host alias
  lineinfile:
    dest: /etc/hosts
    regexp: " netmaster$"
    state: absent
  become: true

- name: remove netctl files
  shell: rm /usr/bin/contiv/netplugin/netctl /usr/bin/netctl /usr/bin/contiv/netplugin/contrib/completion/bash/netctl /etc/bash_completion.d/netctl 

- name: cleanup iptables for contiv network control plane
  shell: iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "{{ netplugin_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ ofnet_master_port }}"
    - "{{ ofnet_agent_port1 }}"
    - "{{ ofnet_agent_port2 }}"
    - "{{ netmaster_port }}"
    - "{{ gobgp_grpc_port }}"
    - "{{ bgp_port }}"
    - "{{ vxlan_port }}"
